// src/redux/actions/types.js
export const ADD_POSITIONS_SUCCESS = "ADD_POSITIONS_SUCCESS";
export const DELETE_POSITIONS_SUCCESS = "DELETE_POSITIONS_SUCCESS";

// Authentication
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// Fetch operations
export const FETCH_FUNCTIONAL_AREAS = "FETCH_FUNCTIONAL_AREAS";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_SECTIONS = "FETCH_SECTIONS";
export const FETCH_SUB_SECTIONS = "FETCH_SUB_SECTIONS";
export const FETCH_POSITIONS = "FETCH_POSITIONS";

// Headcount operations
export const FETCH_HEADCOUNTS_REQUEST = "FETCH_HEADCOUNTS_REQUEST";
export const FETCH_HEADCOUNTS_SUCCESS = "FETCH_HEADCOUNTS_SUCCESS";
export const FETCH_HEADCOUNTS_FAILURE = "FETCH_HEADCOUNTS_FAILURE";
export const UPDATE_HEADCOUNT = "UPDATE_HEADCOUNT";
export const DELETE_HEADCOUNT = "DELETE_HEADCOUNT";
export const ADD_HEADCOUNT = "ADD_HEADCOUNT";
export const BULK_UPDATE_HEADCOUNT = "BULK_UPDATE_HEADCOUNT";
export const BULK_UPDATE_PARENT_ID = "BULK_UPDATE_PARENT_ID";
export const UPDATE_HEADCOUNT_ORDER = "UPDATE_HEADCOUNT_ORDER";

// Project operations
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const FETCH_PROJECT_SECTIONS_SUCCESS = "FETCH_PROJECT_SECTIONS_SUCCESS ";

// Section operations
export const FETCH_SECTIONS_SUCCESS = "FETCH_SECTIONS_SUCCESS";
export const ADD_SECTION_SUCCESS = "ADD_SECTION_SUCCESS";
export const UPDATE_SECTION_SUCCESS = "UPDATE_SECTION_SUCCESS";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS";
export const FETCH_SECTION_SUBSECTIONS_SUCCESS =
  "FETCH_SECTION_SUBSECTIONS_SUCCESS";

// SubSection operations
export const FETCH_SUBSECTIONS_SUCCESS = "FETCH_SUBSECTIONS_SUCCESS";
export const ADD_SUBSECTION_SUCCESS = "ADD_SUBSECTION_SUCCESS";
export const UPDATE_SUBSECTION_SUCCESS = "UPDATE_SUBSECTION_SUCCESS";
export const DELETE_SUBSECTION_SUCCESS = "DELETE_SUBSECTION_SUCCESS";

// Position operations
export const FETCH_POSITIONS_SUCCESS = "FETCH_POSITIONS_SUCCESS";
export const ADD_POSITION_SUCCESS = "ADD_POSITION_SUCCESS";
export const UPDATE_POSITION_SUCCESS = "UPDATE_POSITION_SUCCESS";
export const DELETE_POSITION_SUCCESS = "DELETE_POSITION_SUCCESS";

// Employee operations
export const FETCH_ALL_EMPLOYEE_IDS_SUCCESS = "FETCH_ALL_EMPLOYEE_IDS_SUCCESS";
export const UPDATE_EMPLOYEE_LOCATION_SUCCESS =
  "UPDATE_EMPLOYEE_LOCATION_SUCCESS";
export const UPDATE_EMPLOYEE_IMAGE_SUCCESS = "UPDATE_EMPLOYEE_IMAGE_SUCCESS";
export const UPDATE_RECRUITER_COMMENT_SUCCESS =
  "UPDATE_RECRUITER_COMMENT_SUCCESS";

// History operations
export const FETCH_PROJECT_HISTORY_SUCCESS = "FETCH_PROJECT_HISTORY_SUCCESS";

// Import operations
export const IMPORT_PROJECT_EXCEL_DATA_SUCCESS =
  "IMPORT_PROJECT_EXCEL_DATA_SUCCESS";
export const IMPORT_EMPLOYEE_EXCEL_DATA_SUCCESS =
  "IMPORT_EMPLOYEE_EXCEL_DATA_SUCCESS";

// Baku District, Metro, Target, and Residential Area operations
export const FETCH_BAKU_DISTRICT_EMPLOYEES_SUCCESS =
  "FETCH_BAKU_DISTRICT_EMPLOYEES_SUCCESS";
export const FETCH_BAKU_METRO_EMPLOYEES_SUCCESS =
  "FETCH_BAKU_METRO_EMPLOYEES_SUCCESS";
export const FETCH_BAKU_TARGET_EMPLOYEES_SUCCESS =
  "FETCH_BAKU_TARGET_EMPLOYEES_SUCCESS";
export const FETCH_RESIDENTIAL_AREA_EMPLOYEES_SUCCESS =
  "FETCH_RESIDENTIAL_AREA_EMPLOYEES_SUCCESS";

// Project Sections
// export const FETCH_PROJECT_SECTIONS_SUCCESS = 'FETCH_PROJECT_SECTIONS_SUCCESS';

// Export operations
export const EXPORT_TO_EXCEL_SUCCESS = "EXPORT_TO_EXCEL_SUCCESS";
export const EXPORT_TO_EXCEL_FAILURE = "EXPORT_TO_EXCEL_FAILURE";

//Location Residential area
export const FETCH_RESIDENTIAL_AREA_SUCCESS = "FETCH_RESIDENTIAL_AREA_SUCCESS";
export const FETCH_RESIDENTIAL_AREA_FAILURE = "FETCH_RESIDENTIAL_AREA_FAILURE";
export const FETCH_BAKU_METRO_SUCCESS = "FETCH_BAKU_METRO_SUCCESS";
export const FETCH_BAKU_DISTRICT_SUCCESS = "FETCH_BAKU_DISTRICT_SUCCESS";

export const FETCH_RESIDENTIAL_AREAS = "FETCH_RESIDENTIAL_AREAS";
export const ADD_RESIDENTIAL_AREA = "ADD_RESIDENTIAL_AREA";
export const UPDATE_RESIDENTIAL_AREA = "UPDATE_RESIDENTIAL_AREA";
export const DELETE_RESIDENTIAL_AREA = "DELETE_RESIDENTIAL_AREA";
export const FETCH_EMPLOYEES_IN_RESIDENTIAL_AREA =
  "FETCH_EMPLOYEES_IN_RESIDENTIAL_AREA";

//Colours
export const FETCH_COLOURS = "FETCH_COLOURS";
export const FETCH_COLOURS_FAILURE = "FETCH_COLOURS_FAILURE";
export const FETCH_COLOURS_SUCCESS = "FETCH_COLOURS_SUCCESS";

//Employee

export const FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST";
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_FAILURE = "FETCH_EMPLOYEE_FAILURE";

//Excel Export
export const EXPORT_EXCEL = "EXPORT_EXCEL";
export const EXPORT_EXCEL_SUCCESS = "EXPORT_EXCEL_SUCCESS";
export const EXPORT_EXCEL_FAILURE = "EXPORT_EXCEL_FAILURE";

export const BULK_DELETE = "BULK_DELETE";

export const SET_SELECTED_ROWS = "SET_SELECTED_ROWS";

export const BULK_UPDATE_HEADCOUNT_SUCCESS = "BULK_UPDATE_HEADCOUNT_SUCCESS";
export const BULK_UPDATE_HEADCOUNT_FAIL = "BULK_UPDATE_HEADCOUNT_FAIL";
export const BULK_UPDATE_PARENTID = "BULK_UPDATE_PARENTID";
export const BULK_UPDATE_PARENTID_SUCCESS = "BULK_UPDATE_PARENTID_SUCCESS";
export const BULK_UPDATE_PARENTID_FAIL = "BULK_UPDATE_PARENTID_FAIL";

export const SELECT_ROW = "SELECT_ROW";
export const DESELECT_ROW = "DESELECT_ROW";

export const FETCH_BAKU_DISTRICTS = "FETCH_BAKU_DISTRICTS";
export const ADD_BAKU_DISTRICT = "ADD_BAKU_DISTRICT";
export const UPDATE_BAKU_DISTRICT = "UPDATE_BAKU_DISTRICT";
export const DELETE_BAKU_DISTRICT = "DELETE_BAKU_DISTRICT";

export const FETCH_BAKU_METROS_REQUEST = "FETCH_BAKU_METROS_REQUEST";
export const FETCH_BAKU_METROS_SUCCESS = "FETCH_BAKU_METROS_SUCCESS";
export const FETCH_BAKU_METROS_FAILURE = "FETCH_BAKU_METROS_FAILURE";
export const ADD_BAKU_METRO_SUCCESS = "ADD_BAKU_METRO_SUCCESS";
export const UPDATE_BAKU_METRO_SUCCESS = "UPDATE_BAKU_METRO_SUCCESS";
export const DELETE_BAKU_METRO_SUCCESS = "DELETE_BAKU_METRO_SUCCESS";

export const FETCH_BAKU_TARGET_SUCCESS = "FETCH_BAKU_TARGET_SUCCESS";
export const ADD_BAKU_TARGET = "ADD_BAKU_TARGET";
export const UPDATE_BAKU_TARGET = "UPDATE_BAKU_TARGET";
export const DELETE_BAKU_TARGET = "DELETE_BAKU_TARGET";
export const FETCH_EMPLOYEES_IN_BAKU_TARGET = "FETCH_EMPLOYEES_IN_BAKU_TARGET";

export const FETCH_STORES_SUCCESS = "FETCH_STORES";
export const FETCH_STORE_HISTORY_SUCCESS = "FETCH_STORE_HISTORY_SUCCESS";
export const FETCH_PROJECTS_SUCCESS_STORE = "FETCH_PROJECTS_SUCCESS_STORE";

export const FETCH_ROLES_REQUEST = "FETCH_ROLES_REQUEST";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILURE = "FETCH_ROLES_FAILURE";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

// Fetch Users
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

// Update User
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// Change Password
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

// Delete User
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const SET_FILTER = "SET_FILTER";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const UPDATE_EMPLOYEE_LOCATION = "UPDATE_EMPLOYEE_LOCATION";

export const FETCH_USER_BY_ID_SUCCESS = "FETCH_USER_BY_ID_SUCCESS";
export const FETCH_USER_BY_ID_FAILURE = "FETCH_USER_BY_ID_FAILURE";
